site_name: internetcitizens.band
site_url: http://localhost:8000
repo_url: https://github.com/20centaurifux/fuchsschwanz
theme: bootstrap386
use_directory_urls: false
nav:
        - Home: index.md
        - Topics: topics.md
        - Commands: commands.md
        - Contact: contact.md
plugins: []
